version: '3.6'
services:
  postgres:
    image: postgres:14
    ports:
      - 4321:5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  pgdata:
